name: Testing default install
on: [push]
jobs:
  install-ros2:
    name: Testing ROS2 install scripts
    runs-on: ubuntu-22.04
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Installing
        run: sudo ./scripts/ros2/install.sh
        shell: sh
      - name: ENV exports - sh
        run: ./scripts/ros2/add-exports.sh
        shell: sh
      - name: ENV exports - bash
        run: ./scripts/ros2/add-exports.sh
        shell: bash
      - name: ENV exports - zsh
        run: ./scripts/ros2/add-exports.sh
        shell: zsh
